import localFont from "next/font/local";

const displayFont = localFont({
  src: [
    {
      path: "../token/fonts/TitilliumWeb-Light.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "../token/fonts/TitilliumWeb-Light.woff",
      weight: "300",
      style: "normal",
    },
    {
      path: "../token/fonts/TitilliumWeb-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../token/fonts/TitilliumWeb-Regular.woff",
      weight: "400",
      style: "normal",
    },
    {
      path: "../token/fonts/TitilliumWeb-SemiBold.woff2",
      weight: "600",
      style: "normal",
    },
    {
      path: "../token/fonts/TitilliumWeb-SemiBold.woff",
      weight: "600",
      style: "normal",
    },
    {
      path: "../token/fonts/TitilliumWeb-Bold.woff2",
      weight: "700",
      style: "normal",
    },
    {
      path: "../token/fonts/TitilliumWeb-Bold.woff",
      weight: "700",
      style: "normal",
    },
  ],
  preload: true,
  display: "swap",
  variable: "--ks-font-family-display",
  fallback: [
    "system-ui",
    "-apple-system",
    "BlinkMacSystemFont",
    "Avenir Next",
    "Avenir",
    "Segoe UI",
    "Lucida Grande",
    "Helvetica Neue",
    "Helvetica",
    "Fira Sans",
    "Roboto",
    "Noto",
    "Droid Sans",
    "Cantarell",
    "Oxygen",
    "Ubuntu",
    "Franklin Gothic Medium",
    "Century Gothic",
    "Liberation Sans",
    "sans-serif",
  ],
  adjustFontFallback: false,
});

const interfaceFont = localFont({
  src: [
    {
      path: "../token/fonts/TitilliumWeb-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../token/fonts/TitilliumWeb-Regular.woff",
      weight: "400",
      style: "normal",
    },
    {
      path: "../token/fonts/TitilliumWeb-SemiBold.woff2",
      weight: "600",
      style: "normal",
    },
    {
      path: "../token/fonts/TitilliumWeb-SemiBold.woff",
      weight: "600",
      style: "normal",
    },
    {
      path: "../token/fonts/TitilliumWeb-Light.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "../token/fonts/TitilliumWeb-Light.woff",
      weight: "300",
      style: "normal",
    },
    {
      path: "../token/fonts/TitilliumWeb-Bold.woff2",
      weight: "700",
      style: "normal",
    },
    {
      path: "../token/fonts/TitilliumWeb-Bold.woff",
      weight: "700",
      style: "normal",
    },
  ],
  preload: true,
  display: "swap",
  variable: "--ks-font-family-interface",
  fallback: [
    "system-ui",
    "-apple-system",
    "BlinkMacSystemFont",
    "Avenir Next",
    "Avenir",
    "Segoe UI",
    "Lucida Grande",
    "Helvetica Neue",
    "Helvetica",
    "Fira Sans",
    "Roboto",
    "Noto",
    "Droid Sans",
    "Cantarell",
    "Oxygen",
    "Ubuntu",
    "Franklin Gothic Medium",
    "Century Gothic",
    "Liberation Sans",
    "sans-serif",
  ],
  adjustFontFallback: false,
});

const displayFontPreview = localFont({
  src: [
    {
      path: "../token/fonts/TitilliumWeb-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../token/fonts/TitilliumWeb-Regular.woff",
      weight: "400",
      style: "normal",
    },
    {
      path: "../token/fonts/TitilliumWeb-SemiBold.woff2",
      weight: "600",
      style: "normal",
    },
    {
      path: "../token/fonts/TitilliumWeb-SemiBold.woff",
      weight: "600",
      style: "normal",
    },
    {
      path: "../token/fonts/TitilliumWeb-Light.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "../token/fonts/TitilliumWeb-Light.woff",
      weight: "300",
      style: "normal",
    },
    {
      path: "../token/fonts/TitilliumWeb-Bold.woff2",
      weight: "700",
      style: "normal",
    },
    {
      path: "../token/fonts/TitilliumWeb-Bold.woff",
      weight: "700",
      style: "normal",
    },
  ],
  preload: false,
  display: "auto",
  variable: "--ks-font-family-display",
  fallback: [
    "system-ui",
    "-apple-system",
    "BlinkMacSystemFont",
    "Avenir Next",
    "Avenir",
    "Segoe UI",
    "Lucida Grande",
    "Helvetica Neue",
    "Helvetica",
    "Fira Sans",
    "Roboto",
    "Noto",
    "Droid Sans",
    "Cantarell",
    "Oxygen",
    "Ubuntu",
    "Franklin Gothic Medium",
    "Century Gothic",
    "Liberation Sans",
    "sans-serif",
  ],
  adjustFontFallback: false,
});

const interfaceFontPreview = localFont({
  src: [
    {
      path: "../token/fonts/TitilliumWeb-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../token/fonts/TitilliumWeb-Regular.woff",
      weight: "400",
      style: "normal",
    },
    {
      path: "../token/fonts/TitilliumWeb-SemiBold.woff2",
      weight: "600",
      style: "normal",
    },
    {
      path: "../token/fonts/TitilliumWeb-SemiBold.woff",
      weight: "600",
      style: "normal",
    },
    {
      path: "../token/fonts/TitilliumWeb-Light.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "../token/fonts/TitilliumWeb-Light.woff",
      weight: "300",
      style: "normal",
    },
    {
      path: "../token/fonts/TitilliumWeb-Bold.woff2",
      weight: "700",
      style: "normal",
    },
    {
      path: "../token/fonts/TitilliumWeb-Bold.woff",
      weight: "700",
      style: "normal",
    },
  ],
  preload: false,
  display: "auto",
  variable: "--ks-font-family-interface",
  fallback: [
    "system-ui",
    "-apple-system",
    "BlinkMacSystemFont",
    "Avenir Next",
    "Avenir",
    "Segoe UI",
    "Lucida Grande",
    "Helvetica Neue",
    "Helvetica",
    "Fira Sans",
    "Roboto",
    "Noto",
    "Droid Sans",
    "Cantarell",
    "Oxygen",
    "Ubuntu",
    "Franklin Gothic Medium",
    "Century Gothic",
    "Liberation Sans",
    "sans-serif",
  ],
  adjustFontFallback: false,
});

export const fontClassNames = `${displayFont.variable} ${interfaceFont.variable}`;
export const fontClassNamesPreview = `${displayFontPreview.variable} ${interfaceFontPreview.variable}`;
